# Form implementation generated from reading ui file 'Calorie_calculator.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1117, 717)
        main_window.setStyleSheet("/* Основной фон приложения - глубокий сине-черный */\n"
"QMainWindow, QWidget {\n"
"    background-color: #0d121c;\n"
"    color: #ffffff;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"}\n"
"\n"
"/* Карточки (Сводка, приемы пищи) */\n"
"QFrame {\n"
"    background-color: #1a2230;\n"
"    border-radius: 20px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Элементы списка питания */\n"
"QPushButton#btn_add {\n"
"    background-color: #2a3346;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Акцентная кнопка \"плюс\" с градиентом */\n"
"QPushButton#btn_plus {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #6c63ff, stop:1 #8e88ff);\n"
"    border-radius: 30px;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Таблица и списки */\n"
"QTableWidget, QListWidget {\n"
"    background-color: #1a2230;\n"
"    border: none;\n"
"    outline: none;\n"
"    color: #b0b8c6;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 15px;\n"
"    border-bottom: 1px solid #2a3346;\n"
"}\n"
"\n"
"/* Тексты заголовков */\n"
"QLabel {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Дополнительные подписи (серый цвет) */\n"
"QLabel#label_secondary {\n"
"    color: #7b8596;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #1a2230; /* Цвет фона таблицы */\n"
"    color: #ffffff;           /* БЕЛЫЙ ЦВЕТ ТЕКСТА */\n"
"    gridline-color: #2a3346;  /* Цвет сетки */\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: #ffffff;           /* Гарантированный белый цвет для ячеек */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Настройка заголовков таблицы (чтобы текст в них тоже был виден) */\n"
"QHeaderView::section {\n"
"    background-color: #2a3346;\n"
"    color: #ffffff;           /* Белый текст заголовков */\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: #2a3346;\n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 2px solid #7aa2f7; /* Красивая, заметная серо-голубая рамка */\n"
"    border-radius: 6px;       /* Мягкое скругление углов */\n"
"    padding: 3px 10px;        /* Отступы, чтобы текст не прижимался к краям */\n"
"    background-color: #24283b; /* Фон чуть светлее или темнее основного, чтобы выделялся */\n"
"    color: #c0caf5;           /* Цвет текста */\n"
"}\n"
"\n"
"/* Стиль стрелочки справа */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background: transparent;\n"
"    padding-right: 10px;\n"
"}")
        self.centralwidge = QtWidgets.QWidget(parent=main_window)
        self.centralwidge.setObjectName("centralwidge")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidge)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_photo = QtWidgets.QLabel(parent=self.centralwidge)
        self.lbl_photo.setMinimumSize(QtCore.QSize(250, 250))
        self.lbl_photo.setScaledContents(False)
        self.lbl_photo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_photo.setObjectName("lbl_photo")
        self.verticalLayout_2.addWidget(self.lbl_photo)
        self.btn_load_photo = QtWidgets.QPushButton(parent=self.centralwidge)
        self.btn_load_photo.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_load_photo.setObjectName("btn_load_photo")
        self.verticalLayout_2.addWidget(self.btn_load_photo)
        self.btn_add = QtWidgets.QPushButton(parent=self.centralwidge)
        self.btn_add.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout_2.addWidget(self.btn_add)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.input_weight = QtWidgets.QDoubleSpinBox(parent=self.centralwidge)
        self.input_weight.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.input_weight.setMaximum(10000.0)
        self.input_weight.setObjectName("input_weight")
        self.gridLayout.addWidget(self.input_weight, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.input_name = QtWidgets.QComboBox(parent=self.centralwidge)
        self.input_name.setObjectName("input_name")
        self.gridLayout.addWidget(self.input_name, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.input_kcal = QtWidgets.QDoubleSpinBox(parent=self.centralwidge)
        self.input_kcal.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.input_kcal.setMaximum(90000.0)
        self.input_kcal.setObjectName("input_kcal")
        self.gridLayout.addWidget(self.input_kcal, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 2, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.input_protein = QtWidgets.QDoubleSpinBox(parent=self.centralwidge)
        self.input_protein.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.input_protein.setMaximum(10000.0)
        self.input_protein.setObjectName("input_protein")
        self.gridLayout.addWidget(self.input_protein, 7, 1, 1, 1)
        self.input_fat = QtWidgets.QDoubleSpinBox(parent=self.centralwidge)
        self.input_fat.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.input_fat.setMaximum(10000.0)
        self.input_fat.setObjectName("input_fat")
        self.gridLayout.addWidget(self.input_fat, 9, 1, 1, 1)
        self.input_carbs = QtWidgets.QDoubleSpinBox(parent=self.centralwidge)
        self.input_carbs.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.input_carbs.setMaximum(100000.0)
        self.input_carbs.setObjectName("input_carbs")
        self.gridLayout.addWidget(self.input_carbs, 11, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(17)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(parent=self.centralwidge)
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spin_persons = QtWidgets.QSpinBox(parent=self.centralwidge)
        self.spin_persons.setMinimum(1)
        self.spin_persons.setObjectName("spin_persons")
        self.horizontalLayout.addWidget(self.spin_persons)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_total_kcal = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lbl_total_kcal.setFont(font)
        self.lbl_total_kcal.setMouseTracking(False)
        self.lbl_total_kcal.setObjectName("lbl_total_kcal")
        self.verticalLayout.addWidget(self.lbl_total_kcal)
        self.lbl_portion_kcal = QtWidgets.QLabel(parent=self.centralwidge)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_portion_kcal.setFont(font)
        self.lbl_portion_kcal.setObjectName("lbl_portion_kcal")
        self.verticalLayout.addWidget(self.lbl_portion_kcal)
        self.btn_clear = QtWidgets.QPushButton(parent=self.centralwidge)
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout.addWidget(self.btn_clear)
        self.verticalLayout.setStretch(0, 5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        main_window.setCentralWidget(self.centralwidge)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.lbl_photo.setText(_translate("main_window", "Нет фото"))
        self.btn_load_photo.setText(_translate("main_window", "Загрузить фото"))
        self.btn_add.setText(_translate("main_window", "добавить продукт"))
        self.label_2.setText(_translate("main_window", "Вес (г)"))
        self.label_3.setText(_translate("main_window", "Ккал (на 100г)"))
        self.label.setText(_translate("main_window", "Название продукта"))
        self.label_6.setText(_translate("main_window", "Жиры (на 100г)"))
        self.label_5.setText(_translate("main_window", "Белки (на 100г)"))
        self.label_4.setText(_translate("main_window", "Углеводы(100 г)"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Название"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "вес(г)"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Ккал"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("main_window", "белки"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("main_window", "жиры"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("main_window", "углеводы"))
        self.label_7.setText(_translate("main_window", "количество персон"))
        self.lbl_total_kcal.setText(_translate("main_window", "Итого калорий: 0"))
        self.lbl_portion_kcal.setText(_translate("main_window", "На 1 порцию: 0"))
        self.btn_clear.setText(_translate("main_window", "очистить блюдо"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())
